services:
  - type: web
    name: gaytri-commercial-smart-erp
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/scripts/run_migrations.js && node dist/app.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
