name: gaytri_commercial
description: Gaytri Commercial Management & Attendance App.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management & DI
  provider: ^6.1.2
  
  # Local database & Secure storage
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_secure_storage: ^9.0.0
  
  # Network & Utilities
  http: ^1.2.1
  intl: ^0.20.2
  uuid: ^4.3.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

